### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by scoskey** [aslushnikov/latex-online#11]
I'm not sure why laton is unable to handle this repo. (Tikz is named in the error though.) The repo compiles fine on several machines.

http://latex.aslushnikov.com/compile?git=http://github.com/kbeserra/Thesis&target=main.tex

**Comment by aslushnikov** [comment]
This might happen due to the old version of LiveTex which is currently used on the service (atm it's LiveTex 2012). 

I'll update the docker file as I'll have some spare time - but this is unlikely to happen before weekend. I appreciate any help though :)

**Comment by scoskey** [comment]
Thank you! This is not a hurry, I am just happy you have a public deployment so I don't have to bother trying to create my own. So thanks for that!

**Comment by aslushnikov** [comment]
Great news!

With the new version of Latex-Online, your link compiles successfully!

**Comment by scoskey** [comment]
You da man! Thanks for all your work on this project.
