### ISSUE TITLE
Send file to Api

### ISSUE THREAD

**Issue by asharifi** [aslushnikov/latex-online#12]
Is there anyway to send a tex file directly to the API to use the engine to return pdf in return? If there was not can we do it? If we could, I am willing to help by your guidance

**Comment by aslushnikov** [comment]
Have you seen [laton](https://github.com/aslushnikov/latex-online/blob/master/util/laton) script? Looks like it does what you want: [example](https://github.com/aslushnikov/latex-online#example-1-compile-single-file)

**Comment by asharifi** [comment]
Hmm, Close. Let me make sure that we are on the same page. What I want is a service that has an API endpoint that is able to receive a tex file(or zip file of the whole thing) and return the pdf generated version of that. Laton looks to be a command line script, right?

For example, right now you accept URL, Github repo. I mean adding another one, which is tex file or a compressed package.

**Comment by aslushnikov** [comment]
Ah, yeah, `laton` uses such an api under the hood. At [line 107](https://github.com/aslushnikov/latex-online/blob/master/util/laton#L107) it creates a tarball, which sends via `POST` request to the endpoint  (see [line 112](https://github.com/aslushnikov/latex-online/blob/master/util/laton#L112)).

Will it work for you?

**Comment by asharifi** [comment]
Yes. Right. It does it. Thanks a lot.
