### ISSUE TITLE
Error compiling Git repo

### ISSUE THREAD

**Issue by ktzanev** [aslushnikov/latex-online#15]
Your project looks very interesting !

I have tryed to compile this link : 
`http://latex.aslushnikov.com/compile?git=https://github.com/ktzanev/m53lille1&target=DS/M53_2015-16_Rattrapage.tex`

And the error was : 

    Error: DS/M53_2015-16_Rattrapage.tex:121: graphics `img_ellipse_segment' not found
    compiling DS/M53_2015-16_Rattrapage.tex...
    DS/macros_M53.sty: File `iftex.sty' not found.
    DS/macros_M53.sty:4: Emergency stop.
    DS/macros_M53.sty:4: leading text: \ifPDFTeX

My questions are : 

- Can we compile a file in a sub-folder ?
- What distribution do you use (in general `iftex.sty` is in all standard distributions) ?

**Comment by aslushnikov** [comment]
Thanks for the heads-up!

Indeed, the `iftex.sty` was missing. I've added it in 48dba78dae1058c669497a2956891c194a9b1fd9, everything should work now.

> - Can we compile a file in a sub-folder ?

Yes

> - What distribution do you use (in general iftex.sty is in all standard distributions) ?

The current distribution is a debian jessie with a few additional packages, described in the [Dockerfile](https://github.com/aslushnikov/latex-online/blob/master/Dockerfile)

Hope this helps!
