### ISSUE TITLE
Compile twice

### ISSUE THREAD

**Issue by ktzanev** [aslushnikov/latex-online#16]
When I try to compile the following link : 

`http://latex.aslushnikov.com/compile?git=https://github.com/ktzanev/m53lille1&target=DS/M53_2015-16_Rattrapage.tex`

the compilation works fine, but one of the elements that is positioned in an absolute way on the page using `tikz` needs the source to be compiled twice.

Does latex-online offers a parameter for compiling twice ?

**Comment by aslushnikov** [comment]
No, there's no such argument - it's a bug that it doesn't work for you. Could you please add a screenshot of what is exactly misaligned? This way I would be able to fix the problem.

The `latex-online` relies on [rubber](https://code.launchpad.net/rubber) to build tex. The build system is responsible for running build as many times as needed.

However, the system is not ideal and maybe it is a time to switch to something modern. :)

**Comment by ktzanev** [comment]
When you compile a `tikz` image with the parameters `[remember picture,overlay]` [like here](https://github.com/ktzanev/m53lille1/blob/8851ee2e086aaee165baca446259243c2da1feaf/DS/macros_M53.sty#L165-L169) that allows you to place it anywhere on the page, you have to compile twice.

![example](https://cloud.githubusercontent.com/assets/3259495/16151618/5139f88a-349e-11e6-8dd7-75721ea8e1ca.png)

**Comment by ktzanev** [comment]
I came to see that the other `tikz` images are missing. You can compare your [compiled result](http://latex.aslushnikov.com/compile?git=https://github.com/ktzanev/m53lille1&target=DS/M53_2015-16_Rattrapage.tex) with [my local compilation result](https://ktzanev.github.io/m53lille1/DS/M53_2015-16_Rattrapage.pdf).

**Comment by aslushnikov** [comment]
Interesting. How do you compile this doc? Do you run `pdflatex` twice?

I've tried running [latexrun](https://github.com/aclements/latexrun) on your input, but it reported a lot of syntax errors.

**Comment by ktzanev** [comment]
I was compiling with `xelatex`, but it was supposed to be compatible with `pdflatex` too. BUT, there was a unicode minus sign (`U+2212`) that was not compatible with `pdflatex` (copy/paste problem). Now I have updated the source and it comiles fine with `pdflatex`, with `xelatex` and with `lualatex`. But it is not working with your system.

And yes I compile it twice to have the `T.S.V.P` arrow on the right place.

**Comment by aslushnikov** [comment]
I managed to build your document with some tweaks to the service. Here are the problems that arise:

1. the `latex-online` doesn't know from which folder to build document, so it defaults to the root of the git repository. In your case, it should be the same folder as the target
1. images `img_*` have to be built and committed to the repository separately

(1) might be solved with the `relpath` argument to the API; the (2) is unlikely.

**Comment by ktzanev** [comment]
My mistake : of course the images should be present as pdf in the repo !
So the missing images is not the problem. 

Before `latex-online` was able to compile the document (without some images and with badly positioned one), now it throws an error saying that `macros_M53.sty` is missing, but it is as before present in the same folder.

And I can't find the description of `relpath`. 
Probably the default path should be set to the path of the target ?

**Comment by aslushnikov** [comment]
> Before latex-online was able to compile the document (without some images and with badly positioned one), now it throws an error saying that macros_M53.sty is missing, but it is as before present in the same folder.

Yes, I switched from a very optimistic build system to the one which doesn't tolerate missing imports

> Probably the default path should be set to the path of the target ?

Makes sense; let me fix this

**Comment by aslushnikov** [comment]
This is fixed with f20f05c72fcd91bff05e577f07aa8d10cffbcb57
Your link is now compiling successfully! :)

**Comment by ktzanev** [comment]
:+1: Fantastic ! Thanks.
