### ISSUE TITLE
Compile error --  [babel] Unknown option `czech'

### ISSUE THREAD

**Issue by ondrejtichacek** [aslushnikov/latex-online#21]
Hi, I'm trying to compile my GitHub repository but I'm getting an error

`[babel] Unknown option`czech'`

I have not used latex-online before, but at a first glance, it seems to me that the latex installation is outdated. I am able to compile the repository locally without any problems.

This is the link I used.

http://latex.aslushnikov.com/compile?git=https://github.com/ondrejtichacek/ROZ&target=d.tex

**Comment by aslushnikov** [comment]
Hi Ondřej!
It looks like the language package lacks czech; i'll take a look on the weekend.

**Comment by aslushnikov** [comment]
@ondrejtichacek builds fine for me now!
