### ISSUE TITLE
[babel] No Cyrillic font encoding has been loaded so far

### ISSUE THREAD

**Issue by DidenkoAndre** [aslushnikov/latex-online#23]
Hi Andrey, I'm trying to compile my GitHub repository. Unfortunately, I'm getting an error.

[babel] No Cyrillic font encoding has been loaded so far.
pdfTeX error (font expansion): auto expansion is only possible with scalable fonts.

These errors hint at the lack of packages which are connected to russian language: babel, cm-super, etc.
But as I see, you lived in Russia (it is most likely your homeland) and it is really strange if your service really does not support Russian language. I think there is some another strange mistake. Maybe I did something wrong. I see your diploma-pdf works pretty well. I am very confused.

This is the link I used.
http://latex.aslushnikov.com/compile?git=https://github.com/DidenkoAndre/GOS_book&target=_main.tex

This repo compiles well on my local computer and even on my own server. 

Please, help. This book is aimed to help people prepare for the very important exam. :+1:

**Comment by aslushnikov** [comment]
Hi Andre!

Indeed, the package 'cm-super' wasn't installed on my distribution. However, there seem to be more issues.

I'm out of home today - i'll take a look later as I have time. Hopefully you have some time prior to your exam!

**Comment by aslushnikov** [comment]
Ok, so the link [aslushnikov/GOS_book](http://latex.aslushnikov.com/compile?git=https://github.com/aslushnikov/GOS_book&target=_main.tex) builds for me now. It's slow to process, but it works.

**Comment by DidenkoAndre** [comment]
Thank you! Great work!

**Comment by aslushnikov** [comment]
Good luck with your exams! :)
