### ISSUE TITLE
Add support for multiple compilers (Xelatex, Lualatex)

### ISSUE THREAD

**Issue by MonsieurV** [aslushnikov/latex-online#31]
Hello @aslushnikov,

Love what you're doing here!

I was wondering if this was possible to add multiple compilers support on the API, specified as an optional argument?

A bit like [cli-sharelatex)[https://github.com/sharelatex/clsi-sharelatex] does with the `compilers` option.

The reason behind is: we often have Latex documents that works well with a compiler, but don't work properly on others. (I myself use template that only work on Lualatex)

To support `lualatex`, `pdflatex` and `xelatex` would make the Docker image heavier, but it seems manageable.

What do you think?

I can try a PR for that.

**Comment by aslushnikov** [comment]
Hi @MonsieurV!

Thank you for your interest :)
There's already supports for `xelatex` and `pdflatex`, and I've just added `lualatex`. Here is a usage [example](http://latexonline.cc/compile?url=https%3A%2F%2Fraw.githubusercontent.com%2Faslushnikov%2Flatex-online%2Fmaster%2Fsample%2Fsample.tex&command=lualatex).

Hope this helps!

**Comment by MonsieurV** [comment]
Yes, this is cool!

I have some question on the Rest API, but better ask that in another issue.
