### ISSUE TITLE
Package rmathbr.sty

### ISSUE THREAD

**Issue by LustForLove** [aslushnikov/latex-online#33]
Can you include rmathbr.sty in your TeX-distribution? I get the following error with your compiler: 

`error: File rmathbr.sty not found`

https://ctan.org/pkg/rmathbr 

This package provides re­peat­ing of math op­er­a­tors at the bro­ken line and the new line in in­line equa­tions is used in Cyril­lic math­e­mat­i­cal ty­pog­ra­phy (Rus­sian for ex­am­ple).

**Comment by aslushnikov** [comment]
Also, note: this is now included by default in the new TexLive 2020-based deployment: https://texlive2020.latexonline.cc
