### ISSUE TITLE
Not compiling on Firefox 58.0

### ISSUE THREAD

**Issue by bumbleblue** [aslushnikov/latex-online#43]
I tried to compile the examples on your homepage in Firefox 58.0.2, and it gets stuck. Screenshot below. (My Firefox settings: https://www.privacytools.io/#about_config)
![screen shot 2018-03-16 at 11 27 15](https://user-images.githubusercontent.com/14316263/37516246-68cf6892-2905-11e8-9951-47a63ba88365.png)

**Comment by aslushnikov** [comment]
I just downloaded firefox 59 and the following link loads just fine for me:

https://latexonline.cc/compile?git=https%3A%2F%2Fgithub.com%2Fposquit0%2FAwesome-CV&target=examples%2Fresume.tex&command=xelatex&trackId=1521226377341

Looks like there's some issue with your custom settings. If you're willing to spend some time and figure which setting breaks loading for you, I'd be happy to look into this in near future.

P.S. thanks for taking time and filing the issue!

**Comment by aslushnikov** [comment]
Ah, might be related to #37

**Comment by aslushnikov** [comment]
There's no more google analytics here, so it should work fine now.
