### ISSUE TITLE
Add datetime2.sty

### ISSUE THREAD

**Issue by piraka9011** [aslushnikov/latex-online#48]
Hi, This is a great resource and have used it countless times! Thanks for your contributions!

Is it possible to add the following package to this repo?
https://www.ctan.org/pkg/datetime2

**Comment by piraka9011** [comment]
It looks like datetime2 is included through this [line](https://github.com/aslushnikov/latex-online/blob/e3a70e6cbaae062e26786e7f4a29c7631e6429a2/Dockerfile#L24) in `Dockerfile`. Maybe packages weren't upgraded?

**Comment by aslushnikov** [comment]
Let me update the container on the deployment once #49 is built: https://hub.docker.com/r/aslushnikov/latex-online/builds/byhyfayvnwyeiegpsfav3t7/
