### ISSUE TITLE
Add abntex2.cls

### ISSUE THREAD

**Issue by alanshepard** [aslushnikov/latex-online#49]
Hi! Could you please add the `abntex2` package?
<https://www.ctan.org/pkg/abntex2>

`biblatex-abnt` would also be useful
<https://ctan.org/pkg/biblatex-abnt>

**Comment by aslushnikov** [comment]
@piraka9011 thanks for the reference; added the package. I'll wait for the docker to build and re-launch the deployment.

**Comment by aslushnikov** [comment]
Also, this is included in the latest https://texlive2020.latexonline.cc deployment.
