### ISSUE TITLE
[FIX] Provide latest and greatest full TeX Live 

### ISSUE THREAD

**Issue by dgraziotin** [aslushnikov/latex-online#51]
Hi, I like to have an updated and full LaTeX experience but linux distros obviously need to freeze their packages at a certain point. In [my fork of latex-online](https://github.com/dgraziotin/latex-online/blob/master/Dockerfile) I created a Dockerfile based on yours and @chrisanthropic docker-TeXlive that installs TeX Live manually instead of using the one by Debian Stretch. In addition, `tlmgr update --all` is run as last command to ensure the most updated experience when running Docker. It is working very well for me. Most packages are included, being it the full TeX Live, and issues like #48 and #49 would be already fixed.

Let me know if you like this approach. I can prepare a clean PR.

**Comment by aslushnikov** [comment]
Latex Online now also supports running against `texLive 2020` - https://texlive2020.latexonline.cc
