### ISSUE TITLE
Doesn't work if path contains spaces

### ISSUE THREAD

**Issue by smihael** [aslushnikov/latex-online#53]
If tex is located within git, let's say 'https://github.com/user/repo/folder_with_space rest/_of_the_path.tex', then build will fail:

usage: latexrun [-h] [-o FILE] [--latex-cmd CMD] [--latex-args ARGS]
                [--bibtex-cmd CMD] [--bibtex-args ARGS] [--max-iterations N]
                [-W no-CLASS] [-O DIR] [--color {auto,always,never}]
                [--verbose-cmds] [--debug] [--clean-all]
                [file]
latexrun: error: unrecognized arguments: /_of_the_path.tex'

**Comment by smcjones** [comment]
Just jumping in here - this appears to be a bash input thing. Did you try: 

- Wrapping the name of your file in quotes? 

    "https://github.com/user/repo/folder_with_space rest/_of_the_path.tex" or, 

- Adding a backslash to escape the space? 

    https://github.com/user/repo/folder_with_space\ rest/_of_the_path.tex
