### ISSUE TITLE
How to compile a Tarball via API?

### ISSUE THREAD

**Issue by yegor256** [aslushnikov/latex-online#55]
Is it possible to compile a tarball via the HTTP API? I have a number of files, with the main `article.tex` among them. I want to send them all at once via some PUT or POST request and get the final `article.pdf` back. Is it possible?

**Comment by floh1111** [comment]
Hi @yegor256,  you can use the following API for sending a tarball: `curl -F 'files[]=@/path/to/my.tar.gz' -o ./output.pdf 'http:/localhost:2700/data?command=xelatex&target=document.tex'`

**Comment by aslushnikov** [comment]
@yegor256 check out [latexonline](https://github.com/aslushnikov/latex-online/blob/master/util/latexonline) script - it does precisely this.
