### ISSUE TITLE
insert image when compile with API 

### ISSUE THREAD

**Issue by nguyen179son** [aslushnikov/latex-online#59]
Are there anyway to insert image when using api https://latexonline.cc/compile?... I tried to used base64 to image but its not working.

**Comment by MonsieurV** [comment]
Hi @nguyen179son,

There exist another (experimental & not related) [project](https://github.com/YtoTech/latex-on-http#postbuildssync) with support of `base64` encoded files in the compile payload.

With Latex-Online I think the solution is to [create a tar](https://github.com/aslushnikov/latex-online#3-given-a-tarball-with-files-structure-compile-it) with all your file structure.

**Comment by nguyen179son** [comment]
This message comes out when I try with a tar file. I compress main.tex and image file into a tar.xz file.

> pdflatex -interaction nonstopmode -recorder -output-directory latex.out /tmp/downloads/tmp_14/main.tex
/tmp/downloads/tmp_14/main.tex:1: error: Missing \begin{document}
      at �7zXZ^^@^^@^^D�ִF^^B^^@!^^A^^V^^@^^@^^@t/��'�^^Vi]^^@6^^[�^^Z`қ^^O^^D...
          ^

**Comment by nguyen179son** [comment]
@MonsieurV  This message comes out when I try with a tar file. I compress main.tex and image file into a tar.xz file.
> 
> > pdflatex -interaction nonstopmode -recorder -output-directory latex.out /tmp/downloads/tmp_14/main.tex
> > /tmp/downloads/tmp_14/main.tex:1: error: Missing \begin{document}
> > at �7zXZ^^@^^@^^D�ִF^^B^^@!^^A^^V^^@^^@^^@t/��'�^^Vi]^^@6^^[�^^Z`қ^^O^^D...
> > ^

**Comment by MonsieurV** [comment]
Maybe this is an character encodage issue? Does it work using `laton` command-line tool?

cf https://github.com/aslushnikov/latex-online#example-2-compile-files-with-dependencies

```sh
laton main.tex some-image.jpg 
```

**Comment by aslushnikov** [comment]
This works fine with `laton` CLI tool & git repo fetch. Closing this since discussion has stalled.
