### ISSUE TITLE
The minted package

### ISSUE THREAD

**Issue by Divesh-Otwani** [aslushnikov/latex-online#64]
Could you add support for the minted package?

**Comment by aslushnikov** [comment]
The TexLive 2020 is now live - and I assume it includes everything. Could you please try by either selecting `texlive2020` in the https://latexonline.cc form or using https://texlive2020.latexonline.cc right away?

**Comment by aslushnikov** [comment]
Confirmed that it's supported on the new textlive-based deployment.
