### ISSUE TITLE
Couldn't compile online, but works on pdflatex offline.

### ISSUE THREAD

**Issue by harieamjari** [aslushnikov/latex-online#72]
There was an error I get when trying to compile my tex files online, but the pdflatex on my machine, version pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Termux), compiles it without errors.

Here is the error from latexonline.cc:
```
pdflatex -interaction nonstopmode -recorder -output-directory latex.out /tmp/downloads/tmp_706/main.tex
/tmp/downloads/tmp_706/main.tex:8: error: Missing number, treated as zero
      at <to be read again> t
                            ^
    from \usepackage{geometry}[top=0.5in]
There were errors; /tmp/storage/compilation_669/output.pdf not updated
```
https://latexonline.cc/compile?url=https://gist.githubusercontent.com/harieamjari/f9a48e78c0e084183d77bc3493b5b0b4/raw/271d528d7da0b30cf1b7b8878ab1a793c1913cf5/calculus101.tex&command=pdflatex

**Comment by darshanbeniwal** [comment]
Can you show us your code esp. L8?

**Comment by harieamjari** [comment]
It was included with the url if you didn't know https://github.com/aslushnikov/latex-online/issues/72#issuecomment-881878520

**Comment by darshanbeniwal** [comment]
I meant Latex code not your error snippet. Basically there is an error in L8 of your main tex (as per my knowledge) which might ignored in your offline pdflatex.

**Comment by harieamjari** [comment]
The url of the latex code is part of the `https://latexonline.cc/compile?url=https://gist.githubusercontent.com/harieamjari/f9a48e78c0e084183d77bc3493b5b0b4/raw/271d528d7da0b30cf1b7b8878ab1a793c1913cf5/calculus101.tex&command=pdflatex`

See the `compile?url=`? The next after it is the url of the latex code which is then `https://gist.githubusercontent.com/harieamjari/f9a48e78c0e084183d77bc3493b5b0b4/raw/271d528d7da0b30cf1b7b8878ab1a793c1913cf5/calculus101.tex`

**Comment by darshanbeniwal** [comment]
It works okay for me with texlive2020. Please use Texlive2020 which is available on latexonline.cc

**Comment by harieamjari** [comment]
I just found out that I needed to use the subdomain, texlive2020 to make it work: https://texlive2020.latexonline.cc/compile?url=https://gist.githubusercontent.com/harieamjari/f9a48e78c0e084183d77bc3493b5b0b4/raw/271d528d7da0b30cf1b7b8878ab1a793c1913cf5/calculus101.tex&command=pdflatex
