### ISSUE TITLE
latexonline.cc server offline

### ISSUE THREAD

**Issue by liango96** [aslushnikov/latex-online#88]
The latexonline.cc server seems to be down
<img width="1085" alt="Screenshot 2023-02-10 at 16 58 38" src="https://user-images.githubusercontent.com/83141504/218137528-e81bc81c-8dbd-471b-8640-9e041df13f2f.png">

**Comment by OceanWong1991** [comment]
same question

**Comment by OceanWong1991** [comment]
same question

**Comment by aslushnikov** [comment]
Sorry folks, Iooking into it.

**Comment by aslushnikov** [comment]
Back online. Sorry for the inconvenience!
