### ISSUE TITLE
Latexonline.cc is not reachable: Gateway 502 since this week

### ISSUE THREAD

**Issue by Wesley2712** [aslushnikov/latex-online#95]
![image](https://github.com/aslushnikov/latex-online/assets/39294044/c4638922-005e-4fbd-baad-99bc0db30666)

**Comment by aslushnikov** [comment]
Thanks, working on it

**Comment by aslushnikov** [comment]
Service was migrated to a new server and is back online.
Sorry for the inconvenience!

**Comment by Wesley2712** [comment]
Thank you for solving it, much appreciated!
